project:
  type: hugo
  output-dir: hugo
format:
  hugo-md:
    code-fold: true
execute:
  warning: false
  echo: true
  message: false
  cache: false
engine: knitr
knitr:
  opts_chunk:
    cache.path: .cache/
    cache-path: .cache/
    dev: ragg_png
    out.width: "100%"
editor: source
editor_options:
  chunk_output_type: console
